theme: minima
title: Video Games and Deep Reinforcement Learning Blog
author: 
  name: Ludovic Denoyer
  email: "ludovic.den@gmail.com"

minima:
  social_links:
    twitter: LudovicDenoyer
    github: ludc

google_analytics: G-LNS72EZ5WE

